name: flutter_billing_plugin
description: This plugin supports in-app purchases for App Store (on iOS) or Google Play (on Android).
version: 0.0.8
homepage: https://github.com/techhuntdevelopers/flutter_billing_plugin

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_billing_plugin
        pluginClass: FlutterBillingPlugin
      ios:
        pluginClass: FlutterBillingPlugin


